@echo off
echo Starting Subscription Tracker App...

echo Starting Backend...
start cmd /k "cd backend && node server.js"

echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"

echo Application launching...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:3000 (or 3001 if 3000 is busy)
pause
